name: Feature Request
description: Suggest a new feature
title: '[Feature]: '
labels: [enhancement]
body:
  - type: markdown
    attributes:
      value: Thanks for suggesting a new feature!
  - type: textarea
    id: problem
    attributes:
      label: Problem
      description: Is your feature request related to a problem?
  - type: textarea
    id: solution
    attributes:
      label: Solution
      description: Describe the solution you'd like
    validations:
      required: true
  - type: textarea
    id: alternatives
    attributes:
      label: Alternatives
      description: Any alternatives you've considered
