export const BotEvents = {
  READY: 'ready',
  GUILD_CREATE: 'guildCreate',
  GUILD_DELETE: 'guildDelete',
  GUILD_MEMBER_ADD: 'guildMemberAdd',
  GUILD_MEMBER_REMOVE: 'guildMemberRemove',
  MESSAGE_CREATE: 'messageCreate',
  MESSAGE_DELETE: 'messageDelete',
  MESSAGE_UPDATE: 'messageUpdate',
  INTERACTION_CREATE: 'interactionCreate',
  VOICE_STATE_UPDATE: 'voiceStateUpdate',
  CHANNEL_CREATE: 'channelCreate',
  CHANNEL_DELETE: 'channelDelete',
  CHANNEL_UPDATE: 'channelUpdate',
  GUILD_MEMBER_UPDATE: 'guildMemberUpdate',
  GUILD_ROLE_CREATE: 'guildRoleCreate',
  GUILD_ROLE_DELETE: 'guildRoleDelete',
  GUILD_ROLE_UPDATE: 'guildRoleUpdate',
  GUILD_BAN_ADD: 'guildBanAdd',
  GUILD_BAN_REMOVE: 'guildBanRemove',
  INVITE_CREATE: 'inviteCreate',
  INVITE_DELETE: 'inviteDelete',
  THREAD_CREATE: 'threadCreate',
  THREAD_DELETE: 'threadDelete',
  THREAD_UPDATE: 'threadUpdate',
  STICKER_CREATE: 'stickerCreate',
  STICKER_DELETE: 'stickerDelete',
  STICKER_UPDATE: 'stickerUpdate',
  EMOJI_CREATE: 'emojiCreate',
  EMOJI_DELETE: 'emojiDelete',
  EMOJI_UPDATE: 'emojiUpdate',
  SHARD_READY: 'shardReady',
  SHARD_DISCONNECT: 'shardDisconnect',
  SHARD_RECONNECTING: 'shardReconnecting',
  SHARD_RESUME: 'shardResume',
  ERROR: 'error',
  WARN: 'warn',
  DEBUG: 'debug',
} as const;

export const ApiEvents = {
  GUILD_UPDATE: 'guild:update',
  MODULE_TOGGLE: 'module:toggle',
  TICKET_CREATE: 'ticket:create',
  TICKET_UPDATE: 'ticket:update',
  TICKET_CLOSE: 'ticket:close',
  ECONOMY_TRANSACTION: 'economy:transaction',
  LEVEL_UP: 'level:up',
  ANALYTICS_UPDATE: 'analytics:update',
  PREMIUM_UPDATE: 'premium:update',
  PORTFOLIO_PUBLISH: 'portfolio:publish',
  PORTFOLIO_UPDATE: 'portfolio:update',
  GIVEAWAY_START: 'giveaway:start',
  GIVEAWAY_END: 'giveaway:end',
} as const;
